#!/bin/sh

set -eu

mem_bytes=$(sysctl -n hw.physmem)
mem_gb=$((mem_bytes / 1024 / 1024 / 1024))

# Derived values
maxproc=$((mem_gb * 1024))
maxfiles=$((maxproc * 3))
maxvnodes=$((mem_gb * 20000))

shmmax=$((mem_bytes / 4))
shmall=$((mem_bytes / 4096))

cat <<EOF
# Autogenerated sysctl.conf
# Host RAM: ${mem_gb}GB

# Process / file descriptor ceilings
kern.maxproc=$maxproc
kern.maxfiles=$maxfiles

# Filesystem cache
kern.maxvnodes=$maxvnodes

# Shared memory
kern.shminfo.shmmax=$shmmax
kern.shminfo.shmall=$shmall

# Light network tuning
kern.somaxconn=1024

# Required for X on some hardware
machdep.allowaperture=2
EOF
